export interface Student {
  id: string;
  name: string;
  shape: string;
  traits: string;
  interests: string[];
  theme: string;
  colorPalette: string[];
  fontFamily: string;
  density: number;
  emphasis: string;
  layoutStrategy: string;
  aiExpansionProfile: string;
  printPreset: string;
}

export const STUDENTS: Student[] = [
  {
    id: "1",
    name: "Abby",
    shape: "Teddy bear front-facing",
    traits: "kind, warm, caring, sweet, gentle",
    interests: [],
    theme: "Warm Kindness",
    colorPalette: ["#000000", "#B76E79"],
    fontFamily: "Playfair Display",
    density: 90,
    emphasis: "High",
    layoutStrategy: "Center Dominant",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "2",
    name: "Avery",
    shape: "Graceful girl dancer leaping",
    traits:
      "graceful, athletic, leader, creative, beautiful, honest, funny, smart, caring, friendly, fast, sweet",
    interests: [],
    theme: "bright",
    colorPalette: ["#00BFFF", "#FF69B4"],
    fontFamily: "Impact",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Balanced Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "3",
    name: "CharlieKate",
    shape: "Cheerleader jumping with pom-poms",
    traits: "energetic, loud, spirited, fun, joyful",
    interests: [],
    theme: "Energy and Leadership",
    colorPalette: ["#000000", "#DC143C"],
    fontFamily: "Poppins",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Dynamic Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "4",
    name: "Dominic",
    shape: "Boy dancing energetically",
    traits: "performer, confident, active, cool, fun",
    interests: [],
    theme: "Performance and Confidence",
    colorPalette: ["#000000", "#4169E1"],
    fontFamily: "Oswald",
    density: 85,
    emphasis: "High",
    layoutStrategy: "Motion Focused",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "5",
    name: "Elana",
    shape: "Girl leaping in dance",
    traits: "artistic, excellent, poised, creative, joyful",
    interests: [],
    theme: "Artistic Excellence",
    colorPalette: ["#000000", "#DDA0DD"],
    fontFamily: "Cormorant Garamond",
    density: 80,
    emphasis: "Medium",
    layoutStrategy: "Elegant Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "6",
    name: "Elise",
    shape: "Girl doing ballet arabesque",
    traits: "elegant, classical, precise, beautiful, neat",
    interests: [],
    theme: "Elegance",
    colorPalette: ["#000000", "#FFD700"],
    fontFamily: "Playfair Display",
    density: 80,
    emphasis: "Medium",
    layoutStrategy: "Symmetrical",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "7",
    name: "Emma",
    shape: "Girl singing into microphone",
    traits: "singer, joyful, friendly, loud, happy",
    interests: [],
    theme: "Performance and Joy",
    colorPalette: ["#000000", "#FF00FF"],
    fontFamily: "Montserrat",
    density: 90,
    emphasis: "High",
    layoutStrategy: "Spotlight",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "8",
    name: "Evie",
    shape: "Red panda sitting",
    traits: "adventurous, curious, wild, cute, playful",
    interests: [],
    theme: "Adventure",
    colorPalette: ["#000000", "#CC5500"],
    fontFamily: "Poppins",
    density: 75,
    emphasis: "Medium",
    layoutStrategy: "Organic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "9",
    name: "Evelyn",
    shape: "Dog running",
    traits: "loyal, friendly, steadfast, playful, sweet",
    interests: [],
    theme: "Loyalty and Friendship",
    colorPalette: ["#000000", "#228B22"],
    fontFamily: "Lora",
    density: 75,
    emphasis: "Medium",
    layoutStrategy: "Organic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "10",
    name: "Graham",
    shape: "Boy swinging baseball bat",
    traits: "baseball, captain, strong, athletic, leader",
    interests: [],
    theme: "Team Captain",
    colorPalette: ["#000000", "#000080"],
    fontFamily: "Bebas Neue",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "11",
    name: "Grayson",
    shape: "Boy throwing football",
    traits: "football, competitive, tough, strong, athletic",
    interests: [],
    theme: "Competitive Spirit",
    colorPalette: ["#000000", "#800000"],
    fontFamily: "Oswald",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "12",
    name: "Isabelle",
    shape: "First place ribbon",
    traits: "achiever, excellence, winner, smart, proud",
    interests: [],
    theme: "Achievement",
    colorPalette: ["#000000", "#FFD700"],
    fontFamily: "Cinzel",
    density: 90,
    emphasis: "High",
    layoutStrategy: "Symmetrical",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "13",
    name: "Jace",
    shape: "Video game controller",
    traits: "gamer, tech, logic, smart, fun",
    interests: [],
    theme: "Technology and Creativity",
    colorPalette: ["#000000", "#7DF9FF"],
    fontFamily: "Inter",
    density: 85,
    emphasis: "Medium",
    layoutStrategy: "Geometric",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "14",
    name: "Jack",
    shape: "Eagle in flight",
    traits: "free, soaring, leader, cool, brave",
    interests: [],
    theme: "Freedom and Leadership",
    colorPalette: ["#000000", "#87CEEB"],
    fontFamily: "Montserrat",
    density: 80,
    emphasis: "Medium",
    layoutStrategy: "Organic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "15",
    name: "Landon",
    shape: "Lightning bolt",
    traits: "explosive, energetic, loud, fast, cool",
    interests: [],
    theme: "Energy",
    colorPalette: ["#000000", "#FFA500"],
    fontFamily: "Bebas Neue",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Explosive",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "16",
    name: "Logan",
    shape: "Robot with gears",
    traits: "innovator, gear, engineering, smart, builder",
    interests: [],
    theme: "Innovation",
    colorPalette: ["#000000", "#6A5ACD"],
    fontFamily: "Inter",
    density: 85,
    emphasis: "Medium",
    layoutStrategy: "Technical",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "17",
    name: "Lucy",
    shape: "Horse galloping",
    traits: "strong, graceful, wild, fast, free",
    interests: [],
    theme: "Strength and Grace",
    colorPalette: ["#000000", "#8B4513"],
    fontFamily: "Playfair Display",
    density: 90,
    emphasis: "High",
    layoutStrategy: "Organic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "18",
    name: "Madison",
    shape: "Girl doing gymnastics tumbling",
    traits: "gymnast, determined, flexible, strong, brave",
    interests: [],
    theme: "Determination",
    colorPalette: ["#000000", "#800080"],
    fontFamily: "Poppins",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Dynamic Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "19",
    name: "Max",
    shape: "Pixel game character",
    traits: "creative, funny, pixels, builder, silly",
    interests: [],
    theme: "Creativity and Humor",
    colorPalette: ["#000000", "#50C878"],
    fontFamily: "Orbitron",
    density: 90,
    emphasis: "High",
    layoutStrategy: "Pixel Inspired",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "20",
    name: "Mia",
    shape: "Snake coiled",
    traits: "curious, sneaky, clever, fast, smart",
    interests: [],
    theme: "Curiosity",
    colorPalette: ["#000000", "#50C878"],
    fontFamily: "Lora",
    density: 75,
    emphasis: "Medium",
    layoutStrategy: "Organic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "21",
    name: "Misha",
    shape: "Laptop computer open",
    traits: "laptop, coder, quiet, smart, creative",
    interests: [],
    theme: "Innovation",
    colorPalette: ["#000000", "#008080"],
    fontFamily: "Inter",
    density: 85,
    emphasis: "Medium",
    layoutStrategy: "Technical",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "22",
    name: "Nixon",
    shape: "Football helmet",
    traits: "football, helmet, strong, tough, brave",
    interests: [],
    theme: "Strength",
    colorPalette: ["#000000", "#DC143C"],
    fontFamily: "Oswald",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "23",
    name: "Stephen",
    shape: "Boy kicking soccer ball",
    traits: "soccer, teamwork, fast, runner, strong",
    interests: [],
    theme: "Teamwork",
    colorPalette: ["#000000", "#4CBB17"],
    fontFamily: "Bebas Neue",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "24",
    name: "Torren",
    shape: "Boy making a goalie save",
    traits: "goalie, save, determined, brave, quick",
    interests: [],
    theme: "Determination",
    colorPalette: ["#000000", "#00008B"],
    fontFamily: "Oswald",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
  {
    id: "25",
    name: "Wayde",
    shape: "Boy playing ice hockey",
    traits: "hockey, strong, character, fast, cool",
    interests: [],
    theme: "Strength and Character",
    colorPalette: ["#000000", "#ADD8E6"],
    fontFamily: "Bebas Neue",
    density: 95,
    emphasis: "High",
    layoutStrategy: "Athletic Motion",
    aiExpansionProfile: "Kid-friendly Positive Character Traits",
    printPreset: "Premium Print",
  },
];

export const FONT_OPTIONS = [
  "Bebas Neue",
  "Caveat",
  "Cinzel",
  "Cormorant Garamond",
  "Great Vibes",
  "Impact",
  "Lora",
  "Montserrat",
  "Orbitron",
  "Oswald",
  "Playfair Display",
  "Poppins",
  "Space Grotesk",
  "Inter",
];
export const THEMES = [
  "Classic B&W",
  "Primary School",
  "Athletic",
  "Gold Foil",
  "Soft Watercolor",
  "Modern Minimalist",
];
export const SILHOUETTE_STYLES = [
  "Premium Print",
  "Minimal",
  "Elegant",
  "Modern",
  "Sports",
  "Cartoon",
];
export const OPTIMIZATION_PRESETS = ["Premium Print", "Conservative", "Balanced", "Artistic"];
