/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestHarnessRouteImport } from './routes/test-harness'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateSilhouetteRouteImport } from './routes/api/generate-silhouette'

const TestHarnessRoute = TestHarnessRouteImport.update({
  id: '/test-harness',
  path: '/test-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateSilhouetteRoute = ApiGenerateSilhouetteRouteImport.update({
  id: '/api/generate-silhouette',
  path: '/api/generate-silhouette',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-harness': typeof TestHarnessRoute
  '/api/generate-silhouette': typeof ApiGenerateSilhouetteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-harness': typeof TestHarnessRoute
  '/api/generate-silhouette': typeof ApiGenerateSilhouetteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-harness': typeof TestHarnessRoute
  '/api/generate-silhouette': typeof ApiGenerateSilhouetteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-harness' | '/api/generate-silhouette'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-harness' | '/api/generate-silhouette'
  id: '__root__' | '/' | '/test-harness' | '/api/generate-silhouette'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestHarnessRoute: typeof TestHarnessRoute
  ApiGenerateSilhouetteRoute: typeof ApiGenerateSilhouetteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-harness': {
      id: '/test-harness'
      path: '/test-harness'
      fullPath: '/test-harness'
      preLoaderRoute: typeof TestHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-silhouette': {
      id: '/api/generate-silhouette'
      path: '/api/generate-silhouette'
      fullPath: '/api/generate-silhouette'
      preLoaderRoute: typeof ApiGenerateSilhouetteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestHarnessRoute: TestHarnessRoute,
  ApiGenerateSilhouetteRoute: ApiGenerateSilhouetteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
